# AutoTransform
# Large scale, component based code modification library
#
# Licensed under the MIT License <http://opensource.org/licenses/MIT>
# SPDX-License-Identifier: MIT
# Copyright (c) 2022-present Nathan Rockenbach <http://github.com/nathro>

# A sample workflow that can be used by a repo on Github to schedule automatic
# AutoTransform runs

name: Manage AutoTransform

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  manage-autotransform:
    runs-on: ubuntu-latest
    name: Manage
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Manage AutoTransform
      run: python3 -m autotransform.scripts.main manage --debug
      env:
        PYTHONPATH: /home/runner/work/AutoTransform/AutoTransform/src/python
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}