# AutoTransform
# Large scale, component based code modification library
#
# Licensed under the MIT License <http://opensource.org/licenses/MIT>
# SPDX-License-Identifier: MIT
# Copyright (c) 2022-present Nathan Rockenbach <http://github.com/nathro>

name: Run AutoTransform

on:
  workflow_dispatch:
    inputs:
      schema:
        description: "The name of a Schema in the schema_map"
        required: true
        type: string
      max_submissions:
        description: "The maximum number of submissions when running the schema"
        type: string
        required: false
      filter:
        description: "A filter to add to the schema"
        type: string
        required: false
      target_repo_name:
        description: "The name of the repo to checkout"
        type: string
        required: false
      target_repo_ref:
        description: "The ref of the repo to checkout"
        type: string
        required: false

jobs:
  run-autotransform:
    runs-on: ubuntu-latest
    name: Run
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
        repository: ${{ github.event.inputs.target_repo_name}}
        ref: ${{ github.event.inputs.target_repo_ref}}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Set up options
      run: |
        options="--verbose --name"
        if [[ ! -z "${MAX_SUBMISSIONS}" ]]; then
          options="$options --max-submissions $MAX_SUBMISSIONS"
        fi
        echo "OPTIONS=$options" >> $GITHUB_ENV
      env:
        MAX_SUBMISSIONS: ${{ github.event.inputs.max_submissions }}
    - name: Run AutoTransform
      run: python3 -m autotransform.scripts.main run ${{ env.OPTIONS }} --filter "$FILTER" "${{ github.event.inputs.schema }}"
      env:
        PYTHONPATH: /home/runner/work/AutoTransform/AutoTransform/src/python
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
        FILTER: ${{ github.event.inputs.filter }}