name: Code Review

on:
  pull_request:
    types:
      - opened

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: fxchen/code-review@latest
        with:
          model: 'gpt-4-32k'
          openai-key: ${{ secrets.OPENAI_API_KEY }}
