# AutoTransform
# Large scale, component based code modification library
#
# Licensed under the MIT License <http://opensource.org/licenses/MIT>
# SPDX-License-Identifier: MIT
# Copyright (c) 2022-present Nathan Rockenbach <http://github.com/nathro>

name: Check pylint

on: push

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Check pylint
      run: pylint --enable=W0611,R0902,R0903,R0913,R1732 --disable=C0103,C0411,R0401,R0801,R0914,R0915 src/python/autotransform tests